# Generated by Django 4.1.6 on 2023-02-06 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('industry', models.CharField(default='NHP', max_length=50, verbose_name='Industry')),
                ('name', models.CharField(max_length=100, verbose_name='Station Name')),
                ('category', models.CharField(default='', max_length=10, verbose_name='Category')),
                ('prefix', models.CharField(max_length=64, unique=True, verbose_name='prefix')),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Delay', 'Delay'), ('Offline', 'Offline')], default='Offline', max_length=8)),
                ('state', models.CharField(default='Chattisgarh', max_length=128, verbose_name='state')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('last_reading', models.TextField(default='[]')),
                ('last_reading_at', models.DateTimeField()),
                ('last_file_at', models.DateTimeField()),
                ('parameters', models.TextField(default='[]')),
                ('interval', models.CharField(default=60, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='epan_sites',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('previous_value', models.CharField(default=60, max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtpo_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reading', models.TextField(default='[]')),
                ('timestamp', models.DateTimeField()),
                ('last_file_at', models.DateTimeField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_id', to='mtpo_app.site')),
            ],
            options={
                'unique_together': {('reading', 'site', 'timestamp')},
            },
        ),
    ]
