# Generated by Django 4.1.6 on 2023-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtpo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='last_file_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_reading_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
